MODEL:
  BERT_CKPT: "bert-base-chinese"
  DEVICE: "cuda:0"
  NAME: "bert4csc"
  # [loss_coefficient]
  HYPER_PARAMS: [ 0.5 ]
  GPU_IDS: [0]

DATASETS:
  TRAIN: "datasets/csc/train.json"
  VALID: "datasets/csc/dev.json"
  TEST: "datasets/csc/test.json"

SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.00001
  BATCH_SIZE: 8
  WARMUP_EPOCHS: 2
  MAX_EPOCHS: 10
  ACCUMULATE_GRAD_BATCHES: 16


TEST:
  BATCH_SIZE: 16

TASK:
  NAME: "csc"

OUTPUT_DIR: "checkpoints/bert4csc"
