MODEL:
  BERT_CKPT: "hfl/chinese-macbert-base"
  DEVICE: "cuda:0"
  NAME: "macbert4csc"
  # [loss_coefficient]
  HYPER_PARAMS: [ 0.3 ]
  GPU_IDS: [ 0 ]
#  WEIGHTS: "epoch=6-val_loss=0.07.ckpt"

DATASETS:
  TRAIN: "datasets/csc/train.json"
  VALID: "datasets/csc/dev.json"
  TEST: "datasets/csc/test.json"

SOLVER:
  BASE_LR: 5e-5
  WEIGHT_DECAY: 0.01
  BATCH_SIZE: 32
  MAX_EPOCHS: 10
  ACCUMULATE_GRAD_BATCHES: 4


TEST:
  BATCH_SIZE: 8

TASK:
  NAME: "csc"

OUTPUT_DIR: "checkpoints/macbert4csc"
MODE: [ 'train', "test" ]
